package cz.cvut.kbss.owl2query.model;

public enum KBOperation {
	IS_DIRECT_TYPE, IS_TYPE, GET_DIRECT_INSTANCES, GET_INSTANCES, GET_TYPES, HAS_PROPERTY_VALUE, GET_PROPERTY_VALUE, IS_SAME_AS, GET_SAMES, IS_DIFFERENT_FROM, GET_DIFFERENTS,

	GET_DIRECT_SUB_OR_SUPERCLASSES, GET_EQUIVALENT_CLASSES, IS_SUBCLASS_OF, GET_SUB_OR_SUPERCLASSES, IS_EQUIVALENT_CLASS, IS_DISJOINT_WITH, GET_DISJOINT_CLASSES, IS_COMPLEMENT_OF, GET_COMPLEMENT_CLASSES, GET_DIRECT_SUB_OR_SUPERPROPERTIES, IS_SUBPROPERTY_OF, GET_EQUIVALENT_PROPERTIES, GET_SUB_OR_SUPERPROPERTIES, IS_EQUIVALENT_PROPERTY,
	// IS_INVERSE_OF, GET_INVERSES, IS_OBJECT_PROPERTY,
	// GET_OBJECT_PROPERTIES, IS_DATATYPE_PROPERTY, GET_DATATYPE_PROPERTIES,
	// IS_FUNCTIONAL_PROPERTY, GET_FUNCTIONAL_PROPERTIES,
	// IS_INVERSE_FUNCTIONAL_PROPERTY, GET_INVERSE_FUNCTIONAL_PROPERTIES,
	// IS_TRANSITIVE_PROPERTY, GET_TRANSITIVE_PROPERTIES, IS_SYMMETRIC_PROPERTY,
	// GET_SYMMETRIC_PROPERTIES

}
